### PR TITLE
enable upload_by_url on gologwiki and enable a new config globally

### PR DESCRIPTION
**Pull request by NDKilla**

### CODE REVIEW

**Comment by Southparkfan** [comment]
@NDKilla: you might want to set https://www.mediawiki.org/wiki/Manual:$wgCopyUploadsFromSpecialUpload to true too!

**Comment by addshore** [comment]
Please squash all of this into a single commit:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
and then force push TO THE PULL REQUEST BRANCH :)

**Comment by NDKilla** [comment]
I should probably figure out why the build is failing on the most recent commit before squashing them. I might just redo this later to figure it out >< just looked at it all again

**Comment by addshore** [comment]
Build failure is unrelated but we need to fix our travis config..

    0.01s$ phpenv global 5.4
    /home/travis/build.sh: line 41: phpenv: command not found
    The command "phpenv global 5.4" failed and exited with 127 during .

Im guessing something changed

**Pull request merged**
