### PR TITLE
Custom domain wiki.rohbio.net

### PR DESCRIPTION
**Pull request by PeakFox**
Added entries to point wiki.rohbio.net to rohbiotik.orain.org (DB name rohbiotikwiki).

### CODE REVIEW

**Comment by addshore** [comment]
Is the DNS already set up correctly?
If so someone can probably merge this

**Comment by PeakFox** [comment]
DNS points to prod10.orain.org as per instructions on the orain meta wiki:

;; QUESTION SECTION:
;wiki.rohbio.net.		IN	A

;; ANSWER SECTION:
wiki.rohbio.net.	1799	IN	CNAME	prod10.orain.org.
prod10.orain.org.	299	IN	A	104.28.5.72
prod10.orain.org.	299	IN	A	104.28.4.72

;; Query time: 628 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jun  9 00:01:53 2015
;; MSG SIZE  rcvd: 95

**Comment by addshore** [comment]
Okay, we need to take another look at this due to recent changes mitigating a ddos attack, could you link me to the page with the instructions you followed?

**Comment by PeakFox** [comment]
The instruction page I followed is at https://meta.orain.org/wiki/Tech:Custom_domains

I changed my DNS according to step 3 (see my previous comment), and I followed step 6 for my current commits in this pull request. I finally cross-checked that [my changes](https://github.com/Orain/ansible-playbook/pull/613/files) looked like [the ones in the example](https://github.com/Orain/Ansible-playbook/pull/320/files).

**Comment by Southparkfan** [comment]
Addshore needs to update that guide. He changed DNS to CloudFlare, so this guide is misleading.

**Comment by addshore** [comment]
Updated

**Comment by PeakFox** [comment]
So I understand that according to the revised instructions, there is nothing to do in the ansible-playbook for me as a wiki creator and that the only action required on my part is to set a CNAME for my domain entry wiki.rohbio.net to lb.orain.org (which I've done)?

**Comment by revi** [comment]
I think edit to ansible-playbook is needed to point your domain to your wiki, but I don't think anything beyond that is required.

**Comment by PeakFox** [comment]
In that case, can you go ahead and merge this pull request with the playbook edits? Or what else still needs to be done to get this custom domain working?

**Comment by Southparkfan** [comment]
@PeakFox: wiki.rohbio.net gives me a CloudFlare DNS error, are you sure everything is correctly configured (wiki.rohbio.net should be a CNAME to lb.orain.org)?

**Comment by PeakFox** [comment]
I was wondering about the CloudFlare DNS error too, but I'm positive my DNS is configured correctly.

See http://mxtoolbox.com/SuperTool.aspx?action=a%3awiki.rohbio.net&run=toolpage for confirmation.

Or output from UNIX "dig" using Google nameserver 8.8.8.8 as reference (for example):

>; <<>> DiG 9.8.3-P1 <<>> @8.8.8.8 wiki.rohbio.net
>; (1 server found)
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43260
>;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
>
>;; QUESTION SECTION:
>;wiki.rohbio.net.		IN	A
>
>;; ANSWER SECTION:
>**wiki.rohbio.net.	1799	IN	CNAME	lb.orain.org.**
>lb.orain.org.		299	IN	CNAME	prod10.orain.org.
>prod10.orain.org.	299	IN	A	104.28.4.72
>prod10.orain.org.	299	IN	A	104.28.5.72
>
>;; Query time: 200 msec
>;; SERVER: 8.8.8.8#53(8.8.8.8)
>;; WHEN: Thu Jun 11 22:11:17 2015
>;; MSG SIZE  rcvd: 112

**Comment by addshore** [comment]
I have updated https://meta.orain.org/wiki/Tech:Custom_domains accordingly

**Comment by Southparkfan** [comment]
I'll see if merging the change fixes things.

**Comment by addshore** [comment]
... Why merge it, as I say in the docs currently this is not possible, unless the domain is hosted by us.
I would plan on having a separate LB with a public IP, then people could use it directly.
But currently as we are hiding our IPs the 1 documented solution is the only solution

**Comment by revi** [comment]
Then maybe orain should stop accepting custom domains. Giving over full domain control is too risky and nobody would give full domain access just to have custom wiki.domain.tld, I think. Most custom-domain users will want to use wiki.domain.tld for orain and keep other *.domain.tld under their control.

**Pull request merged**
