### PR TITLE
add WikiSEO to extload

### PR DESCRIPTION
**Pull request by Reception123**
then add to jicigagnon

### CODE REVIEW

**Comment by Reception123** [comment]
@NDKilla

**Comment by Arcane21** [comment]
If this works successfully on extload, could it also be added to ATT as well? We expressed interest in it awhile back, would still like to make use of it.

**Comment by Reception123** [comment]
@addshore add Memento per #715. Could you please merge?

**Comment by addshore** [comment]
We have to download Memento first!

**Comment by Reception123** [comment]
Woops. Ok, ill remove Memento from this pull then.

**Comment by Reception123** [comment]
@addshore @NDKilla Can you merge now?

**Comment by addshore** [comment]
Again.... *facepalm* at 3 commits for a 1 line change.

PLEASE READ http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
or http://davidwalsh.name/squash-commits-git
etc.

If you can't manage that then please open this in a new PR with 1 commit for the single line change!

**Pull request closed without merging**
