### PR TITLE
Revert "download Memento"

### PR DESCRIPTION
**Pull request by NDKilla**
Reverts Orain/ansible-playbook#716

### CODE REVIEW

**Comment by Reception123** [comment]
@NDKilla Why was this reverted this time?

**Comment by NDKilla** [comment]
............................ FUCKKKKKKKK MAH LIFEEEE

Well.. if it should be reverted... someone with roots might have to handle it, because apparently I didn't merge this /pull request/

If it doesn't have to be reverted.. good!

**Comment by NDKilla** [comment]
ndkilla@prod8 /srv/mediawiki/w/extensions
 % cd Memento
ndkilla@prod8 /srv/mediawiki/w/extensions/Memento
 % ls
externals  Makefile  Memento  README.md  scripts  tests

I suppose it doesn't HAVE to be reverted, but puppet downloaded the extension to /srv/mediawiki/w/extensions/Memento/Memento instead of /extensions/Memento (because on the git repo, theres other things and the extension is in a folder... I fixed this in my fork but.. ugh...

**Comment by Reception123** [comment]
@addshore

**Comment by addshore** [comment]
If you want me to fork it just give me the repo you want forked!

**Pull request merged**
