### PR TITLE
add MultiCategorySearch to poserdaz..wiki

### PR DESCRIPTION
**Pull request by Reception123**
per request

### CODE REVIEW

**Comment by Arcane21** [comment]
Doesn't seem to work on ATT, might want to test it first.

https://allthetropes.orain.org/wiki/Special:MultiCategorySearch

**Comment by Reception123** [comment]
How come it does't work? What error could there be?

**Comment by Arcane21** [comment]
Not sure. Didn't see a log error, so it could be an issue with the extension branch that causes it to load but fail to function.

**Comment by NDKilla** [comment]
Closing per Arcane21. Will look into this extension later. Been having other issues too so

**Comment by Reception123** [comment]
@NDKilla Are there still errors?

**Comment by NDKilla** [comment]
@Reception123 I'm not sure? Check on allthetropes.orain.org to see if it works? The extension is still enabled there.

**Pull request closed without merging**
